spring:
  application:
    name: document-assistant
  ai:
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
      chat:
        options:
          model: open-mistral-7b
          temperature: 0.7
    vectorstore:
      pgvector:
        dimensions: 1024
        index-type: hnsw
        initialize-schema: true

management:
  tracing:
    enabled: false
