spring:
  application:
    name: document-assistant
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gtp-3.5-turbo
          temperature: 0.7
    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: hnsw
        initialize-schema: true

management:
  tracing:
    enabled: false
